import asyncio
from playwright.async_api import async_playwright
from http.cookies import SimpleCookie

NETSCAPE_TEMPLATE = """# Netscape HTTP Cookie File
# This file is generated by Playwright automation
# https://curl.se/docs/http-cookies.html
# Example format:
# domain\tflag\tpath\tsecure\texpiration\tname\tvalue
"""

def serialize_cookie(cookie):
    domain = cookie.get('domain', '')
    flag = 'TRUE' if domain.startswith('.') else 'FALSE'
    path = cookie.get('path', '/')
    secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
    expires = int(cookie.get('expires', 0))
    name = cookie['name']
    value = cookie['value']
    return f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}"

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(storage_state="auth.json")

        cookies = await context.cookies()
        with open("cookies.txt", "w", encoding="utf-8") as f:
            f.write(NETSCAPE_TEMPLATE)
            for cookie in cookies:
                f.write(serialize_cookie(cookie) + "\n")

        await browser.close()

asyncio.run(main())
