name: Update cookies.txt

on:
  workflow_dispatch:

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Run script to update cookies.txt
        run: |
          python update_cookies.py

      - name: Commit and push updated cookies.txt
        run: |
          git config user.name "update-bot"
          git config user.email "update-bot@github.com"
          git add cookies.txt
          git commit -m "Update cookies.txt" || echo "no changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
