name: Update cookies.txt

on:
  workflow_dispatch:

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Run script to update cookies.txt
        run: |
          python update_cookies.py

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Commit and push updated cookies.txt
        run: |
          git config user.name "update-bot"
          git config user.email "update-bot@github.com"
          git add cookies.txt
          git commit -m "Update cookies.txt" || echo "no changes"
          git push git@github.com:Sigurd313/yt-dlp-server.git HEAD:main
