name: Update cookies.txt

on:
  workflow_dispatch:

jobs:
  update-cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run cookie update script
        run: python update_cookies.py

      - name: Commit and push updated cookies.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add cookies.txt
          git commit -m "🔁 Auto-update cookies.txt"
          git push
